web_server_location         =   "eastus"
web_server_rg               =   "webapp-rg"
resource_prefix             =   "web-server"
web_server_address_space    =   "1.0.0.0/22"
web_server_address_prefix   =   "1.0.2.0/24"
web_server_name             =   "web-01"